apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: om-mmlogicapi
  labels:
    app: openmatch
    component: mmlogic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: openmatch
      component: mmlogic
  template:
    metadata:
      labels:
        app: openmatch
        component: mmlogic
    spec:
      containers:
      - name: om-mmlogic
        image: gcr.io/matchmaker-dev-201405/openmatch-mmlogicapi:0.4
        imagePullPolicy: Always
        ports:
        - name: grpc
          containerPort: 50503
        - name: metrics
          containerPort: 9555
        resources:
          requests:
            memory: 100Mi
            cpu: 100m
        volumeMounts:
        - name: config
          mountPath: /etc/config/
      volumes:
      - name: config
        configMap:
          name: om-configmap-debug-off
          items:
          - key: om-configmap-debug-off.yaml
            path: matchmaker_config.yaml

